name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: winball.exe
        asset_name: winball.exe
        tag: ${{ github.ref }}
        overwrite: true
        body: "Initial release. Uploaded directly."
